generation_config:
    temperature: 0.90
    top_p: 0.75
    top_k: 50
    num_beams: 2
    use_cache: True
    # max_new_tokens: 64
    max_length: 150
    min_length: 50
    do_sample: True
    
    